version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - ".:/app"
    environment:
      #- REACT_APP_API_URL=http://${DOCKER_MACHINE_IP}:3100
      - CHOKIDAR_USEPOLLING=true
      - CI=true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_volumes"
      - ".:/app"
    command: ["npm", "run", "test"]
